name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
<<<<<<< HEAD
      name: programmeren4Shareameal # naam van mijn environment op GitHub
=======
      name: herokuShareAMeal # naam van mijn environment op GitHub
>>>>>>> feature-express
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: shareameal2177710
          heroku_email: m.haddouch1@student.avans.nl
